"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const user_schema_1 = require("./../schema/user.schema");
const express_1 = __importDefault(require("express"));
const validateResource_1 = __importDefault(require("../middleware/validateResource"));
const user_controller_1 = require("../controller/user.controller");
const userValidation_middleware_1 = require("../middleware/userValidation.middleware");
const router = express_1.default.Router();
router.post("/", (0, validateResource_1.default)(user_schema_1.createUserSchema), userValidation_middleware_1.validateInputUser, user_controller_1.createUserHandler);
router.post("/forgotpassword", (0, validateResource_1.default)(user_schema_1.forgotPasswordSchema), user_controller_1.forgotPasswordHandler);
router.post("/resetpassword/:id/:passwordResetCode", (0, validateResource_1.default)(user_schema_1.resetPasswordSchema), user_controller_1.resetPasswordHandler);
router.get("/me/:accountNo", user_controller_1.getCurrentUserHandler);
router.post("/get", user_controller_1.getUserHandler);
router.put("/save", (0, validateResource_1.default)(user_schema_1.saveAccountTransferSchema), user_controller_1.saveAccountTransferHandler);
router.get("/account-transfer/:userId", user_controller_1.getAccountsTransferHandler);
router.get("/confirm-account-transfer/", user_controller_1.confirmAccountHandler);
exports.default = router;
